### ISSUE TITLE
Update link to workshop materials for IRB fundamentals

### ISSUE THREAD

**Issue by aculich** [dlab-berkeley/IRB-Fundamentals#1]
In https://github.com/dlab-berkeley/IRB-Fundamentals/blob/eae951cb2faeb4a87d633f33b6493142e48fb106/README.md?plain=1#L6 add a [link directly to course materials](https://drive.google.com/drive/folders/1E0nqVOhIt8Ay0ncUSnvP5xPZiPsA8k9j) instead of to the top-level folder with [other workshop materials](https://drive.google.com/drive/folders/1aDcTRXLQDRVViKYKA10-4gmmymRyXlzN). 

Also, the slide deck is currently called [Copy of IRB Slide Deck](https://docs.google.com/presentation/d/1_KvVW1t4thC5BRkxdnO-JdKZ19VHrrOpyB9LDelrZG4/edit#slide=id.g85f3124a96_0_0) so it needs to be renamed and may need some updates. Also, where was it copied FROM? If we have multiple copies floating around we need to resolve that, as well.

**Comment by aculich** [comment]
@rstarowicz Oops.... I accidentally assigned this to you when I meant for it to go to Sev and Vanessa.

**Comment by aculich** [comment]
@Severrinn @vanessa-nr please add a link to any new materials in this [D-Lab Public Data > D-Lab Workshop Materials > IRB shared drive folder](https://drive.google.com/drive/folders/1E0nqVOhIt8Ay0ncUSnvP5xPZiPsA8k9j) and then add comments in the [Workshop Schedule > Workshop List](https://docs.google.com/spreadsheets/d/1FTH3saDimmNTMb6tG9CQ3MkD-tqzXwY854ugzjXB1VE/edit#gid=436321932&range=A44:G44), thanks!

**Comment by pssachdeva** [comment]
Closed by #2.

**Comment by aculich** [comment]
Re-opening this, since to suggest a few other changes to make it easier for end users to find the materials.

Instead export the Google Slides to a PDF file and include that file directly in this repo.

Change the text:

> This repository is a placeholder for D-Lab's IRB Fundamentals workshop. To access the materials, please click on this link.

Instead to something like:

> The materials for this workshop are available as slides: [PDF slides](link/to/repo/pdf) or [Google presentation slides](https://drive.google.com/drive/folders/1E0nqVOhIt8Ay0ncUSnvP5xPZiPsA8k9j)

**Comment by pssachdeva** [comment]
We can definitely include a link to the PDF slides, but I would prefer to keep them in the Google Drive. I am hesitant to include PDF files in GitHub repos for two reasons -

1) It's not generally not good practice since they can't be easily edited, making the version control meaningless.
2) It's extra overhead - every time someone makes a change to the Google Slides, the PDF has to be downloaded, them recommitted to this repo. It's easier for someone to just export to PDF within the Google Drive. It's additionally inflexible, if there are different versions of the slides, which may be the case for IRB Fundamentals (e.g., Vanessa has a few custom slides for an IRB proposal that she personaly led).

For now, I'll include a PDF in the Google Drive, and link to it in the repo.

**Comment by pssachdeva** [comment]
Closing this based of the previous change.
